# // Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# // SPDX-License-Identifier: MIT-0
apiVersion: v1
kind: Pod
spec:
  nodeSelector:
    app: sparktest
    eks.amazonaws.com/capacityType: ON_DEMAND
    # "NodeGroupType": "SparkComputeOptimized"
    # "topology.kubernetes.io/zone": "us-west-2a"    
  volumes:
    - name: spark-local-dir-1
      hostPath:
        path: /local1
        type: Directory
  containers:
  - name: spark-kubernetes-driver # Don't change this name. EMR on EKS looking for this name
    volumeMounts:
      - name: spark-local-dir-1
        mountPath: /data1
        readOnly: false
    # Spark 开源目前不支持定义 affinity https://spark.apache.org/docs/latest/running-on-kubernetes.html#pod-template
    # affinity: 
    #     nodeAffinity: 
    #         requiredDuringSchedulingIgnoredDuringExecution: 
    #           nodeSelectorTerms: 
    #           - matchExpressions: 
    #             - key: 'eks.amazonaws.com/capacityType' 
    #               operator: In 
    #               values: 
    #               - ON_DEMAND
  # tolerations:
  #   - key: "spark-compute-optimized"
  #     operator: "Exists"
  #     effect: "NoSchedule"        