# // Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# // SPDX-License-Identifier: MIT-0
apiVersion: v1
kind: Pod
spec:
  nodeSelector:
    app: sparktest
    # "NodeGroupType": "SparkComputeOptimized"
    # "topology.kubernetes.io/zone": "us-west-2a"    
  volumes:
    - name: spark-local-dir-1
      hostPath:
        path: /local1
        # type: Directory
  # initContainers:  
  # - name: volume-permission
  #   image: public.ecr.aws/y4g4v0z7/busybox
  #   # grant volume access to hadoop user  
  #   command: ['sh', '-c', 'mkdir /data1; chown -R 999:1000 /data1'] 
  #   volumeMounts:
  #     - name: spark-local-dir-1
  #       mountPath: /data1
  containers:
  - name: spark-kubernetes-driver # Don't change this name. EMR on EKS looking for this name
    volumeMounts:
      - name: spark-local-dir-1
        mountPath: /data1
        readOnly: false
  # tolerations:
  #   - key: "spark-compute-optimized"
  #     operator: "Exists"
  #     effect: "NoSchedule"        